"""Generate an index of unfinished backlog.txt entries.

backlog.txt is a single append-only file mixing resolved history (with long
narratives worth keeping for institutional memory) and still-open work. It
has grown past 10,000 lines, so "what's actually still open" is easy to lose
track of -- especially since not every open entry's header says "OPEN":
some are "[PARTIALLY RESOLVED ...]" and some are a bare "[SOME TITLE]" with
no status word at all (never had a resolution note added, but still fully
open).

This script parses backlog.txt's entry headers and writes BACKLOG_OPEN.md,
a short generated index of everything NOT resolved/closed, with line numbers
so you can jump straight to the entry in backlog.txt. It deliberately does
NOT move or duplicate any entry text -- backlog.txt stays the single source
of truth; this is a disposable, regeneratable view onto it.

Usage: python backlog_index.py
(Re-run whenever backlog.txt changes significantly -- there's no hook wired
up to do this automatically.)
"""

from __future__ import annotations

import re
from pathlib import Path

BACKLOG_PATH = Path(__file__).parent / "backlog.txt"
OUTPUT_PATH = Path(__file__).parent / "BACKLOG_OPEN.md"

# A finished decision either way -- excluded from the "still unfinished" index.
_DONE_PREFIXES = ("RESOLVED", "CLOSED")


def parse_entries(text: str) -> list[dict]:
    """Split backlog.txt into entries anchored on '[' at column 0, and
    return one dict per entry: {line, status, title}.

    An entry's header can wrap across multiple indented continuation lines
    before its "Priority:" line starts -- e.g.:
        [OPEN -- found via adjacency 2026-07-30 during Snow Step 2's opus
          review round 2] COUNT_SETTLED_PREDICTIONS() HAS NO CONDITION_TYPE
          FILTER -- ...
        Priority: Medium ...
    so the bracket tag and the entry title are joined across those lines
    before splitting on the first ']'.
    """
    lines = text.splitlines()
    header_line_nums = [i for i, line in enumerate(lines) if line.startswith("[")]

    entries = []
    for line_idx in header_line_nums:
        # Collect this header's own line plus indented continuation lines
        # until "Priority:" (every real entry has one) or a blank line.
        block = [lines[line_idx]]
        j = line_idx + 1
        while j < len(lines):
            nxt = lines[j]
            if nxt.strip() == "" or nxt.startswith("Priority:"):
                break
            block.append(nxt)
            j += 1
        header_text = " ".join(s.strip() for s in block)

        match = re.match(r"\[(.*?)\]\s*(.*)", header_text, re.DOTALL)
        if not match:
            continue  # malformed/unexpected shape -- skip rather than guess
        bracket_content, title = match.group(1).strip(), match.group(2).strip()

        status = next(
            (p for p in _DONE_PREFIXES if bracket_content.startswith(p)), None
        )
        if status:
            continue  # finished either way -- not part of the "open" index

        # Bracket had no title after it (bare-bracket entries put the whole
        # thing inside the brackets, e.g. "[MOVE OFF LOCAL CRON ...]").
        if not title:
            title = bracket_content
            bracket_content = ""

        if bracket_content.startswith("PARTIALLY RESOLVED"):
            tag = "PARTIALLY RESOLVED"
        elif bracket_content.startswith("OPEN"):
            tag = "OPEN"
        else:
            tag = "OPEN"  # bare-bracket, no status word -- still fully open

        entries.append({"line": line_idx + 1, "tag": tag, "title": title.rstrip(" -")})
    return entries


def render(entries: list[dict]) -> str:
    out = [
        "# Backlog — Unfinished Items (auto-generated)",
        "",
        "Generated by `python backlog_index.py` from `backlog.txt`. This file "
        "is a disposable index, not a source of truth -- edit backlog.txt "
        "itself, then re-run the script to refresh this list. RESOLVED and "
        "CLOSED entries (finished either way) are excluded.",
        "",
        f"**{len(entries)} unfinished entries** as of generation time.",
        "",
    ]
    for e in entries:
        out.append(f"- **L{e['line']}** [{e['tag']}] {e['title']}")
    out.append("")
    return "\n".join(out)


def main() -> None:
    text = BACKLOG_PATH.read_text(encoding="utf-8")
    entries = parse_entries(text)
    OUTPUT_PATH.write_text(render(entries), encoding="utf-8")
    print(f"Wrote {len(entries)} unfinished entries to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
